title: 심플하고 여유있는 삶
email: suchme@gmail.com
description: |-
  국제사이버범죄연구센터 선임연구원
  관심분야 : Cybercrime, Digital forensics, Data Analysis
baseurl: ''
url: ''
twitter_username: 'j1h0'
github_username: j1h0
facebook_username: jh10.s
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin
